
### Criar Asset
# @name createAsset
POST http://localhost:3000/assets
Content-Type: application/json
[ 
    {
        "name": "Amazon",
        "symbol": "AMZN",
        "price": 100,
        "image": "AMZN.png"
    },
    {
        "name": "Sales",
        "symbol": "SAL",
        "price": 200,
        "image": "CRM.png"
    },
    {
        "name": "Google",
        "symbol": "GOOG",
        "price": 300,
        "image": "GOOGL.png"
    },
    {
        "name": "Coca-Cola",
        "symbol": "KO",
        "price": 400,
        "image": "KO.png"
    },
    {
        "name": "Mac Donalds",
        "symbol": "MCD",
        "price": 500,
        "image": "MCD.png"
    },
    {
        "name": "Mercado Livre",
        "symbol": "MELI",
        "price": 600,
        "image": "MELI.png"
    },
    {
        "name": "Facebook",
        "symbol": "META",
        "price": 700,
        "image": "META.png"
    },
    {
        "name": "Ndivia",
        "symbol": "NVDA",
        "price": 800,
        "image": "NVDA.png"
    },
    
]
###

POST http://localhost:3000/assets
Content-Type: application/json

    {
        "name": "Google",
        "symbol": "GOOG",
        "price": 300,
        "image": "GOOGL.png"
    }

###

@assetId = {{ createAsset.response.body._id }}

###

GET http://localhost:3000/assets


###

GET http://localhost:3000/assets/A1

###
# @name createWallet
POST http://localhost:3000/wallets
Content-Type: application/json

###

@walletId = {{ createWallet.response.body._id }}

###

GET http://localhost:3000/wallets


###

GET http://localhost:3000/wallets/{{walletId}}

###

POST http://localhost:3000/wallets/{{walletId}}/assets
Content-Type: application/json

{
    "assetId": "{{ assetId }}",
    "shares": 100
}

###

POST http://localhost:3000/orders
Content-Type: application/json

{
    "walletId": "{{ walletId }}",
    "assetId": "{{ assetId }}",
    "shares": 10,
    "price": 10,
    "type": "BUY"
}

###

GET http://localhost:3000/orders?walletId={{walletId}}

